"""Add reporter_contact column to lost_item

Revision ID: 49f615708932
Revises: 067a381ee387
Create Date: 2024-08-09 19:20:00.404042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f615708932'
down_revision = '067a381ee387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add 'reporter_contact' column as nullable first
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_contact', sa.Integer(), nullable=True))
    
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_contact', sa.Integer(), nullable=True))
    
    # Optionally, update existing rows with a default value
    # Uncomment these lines if you want to set a default value for existing rows
    # op.execute('UPDATE found_item SET reporter_contact = 0 WHERE reporter_contact IS NULL')
    # op.execute('UPDATE lost_item SET reporter_contact = 0 WHERE reporter_contact IS NULL')

    # Alter column to be NOT NULL if needed
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.alter_column('reporter_contact', existing_type=sa.Integer(), nullable=False)
    
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.alter_column('reporter_contact', existing_type=sa.Integer(), nullable=False)
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.drop_column('reporter_contact')
    
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.drop_column('reporter_contact')
    # ### end Alembic commands ###

