"""Add date_reported column to LostItem

Revision ID: eb8cf36f6245
Revises: c54a15900fc2
Create Date: 2024-07-01 18:49:18.665699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8cf36f6245'
down_revision = 'c54a15900fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_reported', sa.DateTime(), nullable=True))
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('date_found')

    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_reported', sa.DateTime(), nullable=True))
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('date_lost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_lost', sa.DATETIME(), nullable=False))
        batch_op.alter_column('photo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('date_reported')

    with op.batch_alter_table('found_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_found', sa.DATETIME(), nullable=False))
        batch_op.alter_column('photo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('date_reported')

    # ### end Alembic commands ###
